#pragma once
namespace quasar {
struct FloatParameter{const char* id;const char* name;double Settings::*member;};
inline constexpr FloatParameter floatParameters[]={
 {"matter","MATTER",&Settings::matter},
 {"field","FIELD",&Settings::field},
 {"particles","PARTICLES",&Settings::particles},
 {"plasma","PLASMA",&Settings::plasma},
 {"coupling","TENSEGRITY",&Settings::coupling},
 {"motion","MOTION",&Settings::motion},
 {"evolve","EVOLVE",&Settings::evolve},
 {"space","SPACE",&Settings::space},
 {"energy","ENERGY",&Settings::energy},
 {"pulse","PULSE",&Settings::pulse},
 {"tone","MATTER TONE",&Settings::tone},
 {"structure","MATTER STRUCTURE",&Settings::structure},
 {"density","Density",&Settings::density},
 {"attack","MATTER ATTACK (seconds)",&Settings::attack},
 {"release","MATTER RELEASE (seconds)",&Settings::release},
 {"force","EXCITER FORCE",&Settings::force},
 {"hardness","EXCITER HARDNESS",&Settings::hardness},
 {"position","EXCITER POSITION",&Settings::position},
 {"speed","EXCITER SPEED",&Settings::speed},
 {"fieldShape","FIELD SHAPE",&Settings::fieldShape},
 {"fieldBrightness","FIELD BRIGHTNESS",&Settings::fieldBrightness},
 {"fieldModulation","FIELD MODULATION",&Settings::fieldModulation},
 {"fieldSpread","FIELD SPREAD",&Settings::fieldSpread},
 {"particleRate","PARTICLE RATE",&Settings::particleRate},
 {"particleDecay","PARTICLE DECAY",&Settings::particleDecay},
 {"particlePitch","PARTICLE PITCH / SIZE",&Settings::particlePitch},
 {"particleSpread","PARTICLE SPREAD",&Settings::particleSpread},
 {"particleSelf","PARTICLE SELF",&Settings::particleSelf},
 {"particleImpact","PARTICLE IMPACT",&Settings::particleImpact},
 {"plasmaSelf","PLASMA SELF",&Settings::plasmaSelf},
 {"plasmaDrive","PLASMA DRIVE",&Settings::plasmaDrive},
 {"plasmaFlow","PLASMA FLOW",&Settings::plasmaFlow},
 {"plasmaPressure","PLASMA PRESSURE",&Settings::plasmaPressure},
 {"plasmaTurbulence","PLASMA TURBULENCE",&Settings::plasmaTurbulence},
 {"plasmaScale","PLASMA SCALE",&Settings::plasmaScale},
 {"plasmaRate","PLASMA RATE",&Settings::plasmaRate},
 {"plasmaCoherence","PLASMA COHERENCE",&Settings::plasmaCoherence},
 {"plasmaIntermittency","PLASMA INTERMITTENCY",&Settings::plasmaIntermittency},
 {"plasmaResonance","PLASMA RESONANCE",&Settings::plasmaResonance},
 {"fieldStructure","FIELD STRUCTURE",&Settings::fieldStructure},
 {"fieldTone","FIELD TONE",&Settings::fieldTone},
 {"fieldAttack","FIELD ATTACK (seconds)",&Settings::fieldAttack},
 {"fieldRelease","FIELD RELEASE (seconds)",&Settings::fieldRelease},
 {"pulseRate","PULSE RATE",&Settings::pulseRate},
};
struct ChoiceParameter{const char* id;const char* name;int Settings::*member;const char* choices;int count;};
inline constexpr ChoiceParameter choiceParameters[]={
 {"matterModel","MATTER MODEL",&Settings::matterModel,"Original|String|Bar|Plate|Membrane|Glass|Bell|Weird",8},
 {"exciter","MATTER EXCITER",&Settings::exciter,"Strike|Pluck|Friction|Air|Scrape|Weird",6},
 {"fieldModel","FIELD MODEL",&Settings::fieldModel,"Original|Harmonic|Stretched|FM|Cluster|Hollow|Shimmer|Dense|Weird|Wave|Coupled",11},
 {"particleModel","PARTICLE MODEL",&Settings::particleModel,"Ring|Drop|Spark|Knock|Chirp|Scrape|Bubble|Dust|Weird",9},
 {"plasmaModel","PLASMA MODEL",&Settings::plasmaModel,"Flow|Storm|Chaos|Surf|Foliage|Rain|Granular|Crackle|Boil|Vortex|Drift|Weird",12},
};
constexpr int floatCount=sizeof(floatParameters)/sizeof(FloatParameter),choiceCount=sizeof(choiceParameters)/sizeof(ChoiceParameter),parameterCount=floatCount+choiceCount;
}
